apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-frontend
  labels:
    app: todoapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp-frontend
  template:
    metadata:
      labels:
        app: todoapp-frontend
    spec:
      containers:
        - name: todoapp-frontend
          image: registry.digitalocean.com/csc5201-ianm/task-frontend-0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
          - name: regsecret

---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-frontend
spec:
  selector:
    app: todoapp-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80          # External port for the frontend
      targetPort: 80    # Internal container port for Nginx
