apiVersion: v1
kind: Service
metadata:
  name: todo-api
spec:
  selector:
    app: todo-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8888        # External port
      targetPort: 5000  # Internal container port